### ISSUE TITLE
Syntax-Error

### ISSUE THREAD

**Issue by happycamper31** [CounterPillow/srcomdumpy#1]
Hi,

I downloaded the 3 files and tried to run it, but get a syntax error where it looks that it comes from within the script and not my input.

```
line 27
    return f"Leaderboard(game_id={self.game_id}, category_ids=[{", ".join(self.category_ids)}])"
                                                                 ^
SyntaxError: f-string: expecting '}'
```
Btw that came when I tried to execute:
`./srcomdumpy.py -h`

BR happycamper

**Comment by CounterPillow** [comment]
This is because your old Python version does not support this f-string syntax yet. I'll look into adding compatibility; what is your output of `python3 --version`, and which distribution is this on?

**Comment by CounterPillow** [comment]
Fixed the problem. To reproduce, I quickly whipped up a Ubuntu 22.04 container, which is probably close to an installation you were using, with mkosi:

```
mkosi -dubuntu -rjammy -tdirectory -ppython3,python3-urllib3,ca-certificates -oubuntu-jammy-python build
```

This will give us an OS tree in the `ubuntu-jammy-python` directory with python3, python3-urllib3 and ca-certificates installed.

Next, I ran the container with systemd-nspawn with the script location bound into the container, using the following command, as root (e.g. via sudo or run0):

```
systemd-nspawn --bind-ro=/path/to/srcomdumpy -x -D ubuntu-jammy-python /path/to/srcomdumpy/srcomdumpy.py https://www.speedrun.com/gtacw
```

This allowed me to quickly reproduce the problem, which has now been fixed.

Update your git checkout with `git pull` (or redownload the files if you're doing it that way) and you can run the script now as per the README.md instructions.

**Comment by happycamper31** [comment]
Thanks, now it runs without an error!
I have a totally unrelated problem though: The formatting of the output is "questionable". I cannot find any of the runners names. But it looks like links to runs & run-comments are in there. Idk what to make of that :D 

For completeness my version is Python 3.10.12

**Comment by CounterPillow** [comment]
The runners names can change, hence why the output is the ID of the user accounts. I can add functionality to resolve the names while downloading as well and add them as an additional column/key to the output.

**Comment by happycamper31** [comment]
Ah, makes sense. More functionality would be cool, but it's also fine once you know it's only id.
